--- #YAML:1.0
name:                Template-Plugin-Filter-Minify-CSS
version:             0.92
abstract:            CSS::Minifier filter for Template Toolkit
license:             ~
author:              
    - Michael Schout <mschout@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CSS::Minifier:                 0
    Template:                      2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
