---
abstract: 'CSS::Minifier filter for Template Toolkit'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Filter-Minify-CSS
requires:
  CSS::Minifier: 0
  Template: 2.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Filter-Minify-CSS
  homepage: http://search.cpan.org/dist/Template-Plugin-Filter-Minify-CSS/
  repository: http://github.com/mschout/template-plugin-filter-minify-css
version: 0.93
